some: tests
more:
  tests: 123


# Effect section in a random config file ...
# Triggers must be compatible with the effects defined above
effects:
  - id: damage_multiplier
    multiplier: "1.25"
    # define unlimited variables for each effect
    # Each effect can have its own variables
    something: 123
    # can be single or a list
    # All defined triggers must be compatible with the filters below!
    triggers:
      - melee_attack
      - bow_attack
      - trident_attack
    # The conditions required for the effect to activate
    # This conditions are not bind to the triggers
    # The filters are bind to the triggers below!
    conditions: [ ]
    # The filters required for the effect to activate
    # Must be compatible with all the triggers defined above
    filters: [ ]

# Conditions section in a random config file ...
# We must need to give this section to NexLogic and ask, if the conditions are met,
# nothing more in this case
conditions: [ ]


# Triggers section in a random config file ...
# We must need to give this section to NexLogic and ask, if something was triggered with this section.
# triggers and effects need filters and conditions!
triggers:
  - id: melee_attack
    conditions: [ ]
    filters:
      - id: entity
        # can be single or a list
        entity:
          - 'minecraft:zombie'
          - 'minecraft:skeleton'
    effects:
      - id: damage_multiplier
        multiplier: "1.25"
        conditions: [ ]
        filters: [ ]